name: bitplus
description: An habit tracket and diary to create balance in your life flow
author: Sandro Maglione <lass.maglio@gmail.com>
homepage: https://www.sandromaglione.com

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.0.3

  # Bloc for state management
  flutter_bloc: ^2.1.1

  # Value equality
  equatable: ^1.0.1

  # Functional programming thingies
  dartz: ^0.8.7

  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2

  # Local cache
  shared_preferences: ^0.5.6

  # json serialization
  json_annotation: ^3.0.0
  built_value: ^7.0.0
  built_collection: ^4.3.0

  # bloc support enum
  super_enum: ^0.2.0

  # google sign-in
  google_sign_in: ^4.1.0

  # firebase
  firebase_core: ^0.4.3
  firebase_analytics: ^5.0.9
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^6.0.9
  firebase_crashlytics: ^0.1.2+4
  firebase_performance: ^0.3.1+5

  # auto router
  auto_route: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  # json serialization
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  # bloc support enum generator
  super_enum_generator: ^0.2.0+1
  # auto router
  auto_route_generator: ^0.2.0


flutter:
  uses-material-design: true