library user_account;

import 'dart:convert';

import 'package:bitplus/core/serializers/serializers.dart';
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'post_user_account.g.dart';

/// Send user account credentials after sign up to store inside database
/// 
/// [uid] autogenerated after sign up call successful
abstract class PostUserAccount
    implements Built<PostUserAccount, PostUserAccountBuilder> {
  factory PostUserAccount([Function(PostUserAccountBuilder b) updates]) =
      _$PostUserAccount;

  PostUserAccount._();

  String get uid;
  String get email;
  BuiltList<int> get areas;

  String toJson() {
    return json.encode(
      serializers.serializeWith(
        PostUserAccount.serializer,
        this,
      ),
    );
  }

  static PostUserAccount fromJson(String jsonString) {
    return serializers.deserializeWith(
      PostUserAccount.serializer,
      json.decode(
        jsonString,
      ),
    );
  }

  static Serializer<PostUserAccount> get serializer =>
      _$postUserAccountSerializer;
}
